from keras.optimizers import SGD, Adam

# General data parameters
DATASET_PATH = 'dataset-resized'
SHUFFLE_DATA = True

# Data generator parameters
TRAINING_BATCH_SIZE = 128
TRAINING_IMAGE_SIZE = (256,256)
VALIDATION_BATCH_SIZE = 324
VALIDATION_IMAGE_SIZE = TRAINING_IMAGE_SIZE
VALIDATION_DATASET_SIZE = 324
TESTING_BATCH_SIZE = 324
TESTING_IMAGE_SIZE = TRAINING_IMAGE_SIZE
TEST_DATASET_SIZE = 324
NUMBER_OF_CHANNELS = 3
TRANSFORM = True


# Model parameters
NBNEURONE1 = 256
NBNEURONE2 = 128
NBNEURONE3 = 128
NBNEURONE4 = 64
NBNEURONE5 = 6
TAUX_APPRENTISAGE = 0.001
NBEPOCH = 200
DESCENTEGRAD = Adam(TAUX_APPRENTISAGE)
DROPOUT=0.4

# Values for metric
WORK_PER_PERSON_FOR_TWENTY_MINS = 80.54
MARGIN = 9