from keras.optimizers import SGD, Adam

# General data parameters

DATASET_PATH = 'dataset-resized'
SHUFFLE_DATA = True

# Data generator parameters
TRAINING_BATCH_SIZE = 128
TRAINING_IMAGE_SIZE = (128, 128)
VALIDATION_BATCH_SIZE = 324
VALIDATION_IMAGE_SIZE = TRAINING_IMAGE_SIZE
VALIDATION_DATASET_SIZE = 324
TESTING_BATCH_SIZE = 324
TESTING_IMAGE_SIZE = TRAINING_IMAGE_SIZE
TEST_DATASET_SIZE = 324
NUMBER_OF_CHANNELS = 3
TRANSFORM = True


# Model parameters
NBNEURONE1 = 128
NBNEURONE2 = 6
taux_apprentissage = 0.0004
NBEPOCH = 1
descenteGrade = Adam(taux_apprentissage)

# Values for metric
WORK_PER_PERSON_FOR_TWENTY_MINS = 80.54
MARGIN = 9